dctb-mysql:
  container_name: dctb-mysql
  image: mysql
  volumes:
    - "./mysql:/var/lib/mysql"
  environment:
    MYSQL_ROOT_PASSWORD : root
    MYSQL_DATABASE      : base
    MYSQL_USER          : root
    MYSQL_PASSWORD      : root
dctb-phpmyadmin:
  container_name: dctb-phpmyadmin
  image: corbinu/docker-phpmyadmin
  links:
    - dctb-mysql:mysql
  ports:
    - "9999:80"
  environment:
    MYSQL_USERNAME      : root
    MYSQL_ROOT_PASSWORD : root
dctb-wordpress:
  container_name: dctb-wordpress
  image: diogocezar/wordpress
  links:
    - dctb-mysql
  volumes:
    - "./www:/var/www"
  ports:
    - "8888:80"
    - "2222:22"